let firstPasswordEl = document.getElementById("firstPassword")
let secondPasswordEl = document.getElementById("secondPassword")
let buttonEl = document.getElementById("generatePassword")
let myRangeEl = document.getElementById("rangeValue")
let copytextEl = document.querySelectorAll(".copytext")

// password array to store 2 passwords. passwordLength to define the length of the string. random

// let password = ["",""]
let password = ""
let passwordLength = ""
let index = ""


console.log(passwordLength)

const characters = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9","~","`","!","@","#","$","%","^","&","*","(",")","_","-","+","=","{","[","}","]",",","|",":",";","<",">",".","?",
"/"];


function randomCharacters(){
    let index = Math.floor(Math.random() * characters.length - 1) 
    return index
}

console.log(randomCharacters())
// when clicked on the element then run the generatePassword() function

buttonEl.addEventListener("click", generatePassword) 

// if password field lenth is 0 by default then run generatePassword() function

if(firstPasswordEl.textContent.length === 0){
    generatePassword()
} else{
    reset()
}

// for loop -> concats characters from array using a random index generated by the randomCharacters() function

function generatePassword(){
    let passwordLength = myRangeEl.innerText
    for (let i = 0; i < passwordLength; i++){
        password += characters[randomCharacters()]
        // password[1] += characters[randomCharacters()]
        // password[2] += characters[randomCharacters()]
    }
console.log(randomCharacters())

    firstPasswordEl.textContent = password
    // secondPasswordEl.textContent = password[2]

    reset()
}


// function copyDivToClipboard(){

//     alert(firstPasswordEl.value + "Copied to clipboard")
// }

// reset the value of the elements within the array

function reset(){
    password = ""
    // password[1] = ""
    // password[2] = ""    
}
